# from PyQt6 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Dialog(object):
#     def setupUi(self, Dialog):
#         Dialog.setObjectName("Dialog")
#         Dialog.resize(350, 339)
#         self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
#         self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 10, 151, 281))
#         self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
#         self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
#         self.verticalLayout.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.Number = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
#         self.Number.setObjectName("Namevhod")
#         self.verticalLayout.addWidget(self.Number)
#         self.Date = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
#         self.Date.setObjectName("Date")
#         self.verticalLayout.addWidget(self.Date)
#         self.Agent = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
#         self.Adress.setObjectName("Agent")
#         self.verticalLayout.addWidget(self.Agent)
#         self.Sum = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
#         self.Sum.setObjectName("Contact")
#         self.verticalLayout.addWidget(self.Sum)
#
#         self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
#         self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 160, 281))
#         self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
#         self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
#         self.label_4.setObjectName("label_4")
#         self.verticalLayout_2.addWidget(self.label_4)
#         self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
#         self.label_6.setObjectName("label_6")
#         self.verticalLayout_2.addWidget(self.label_6)
#         self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
#         self.label_2.setObjectName("label_2")
#         self.verticalLayout_2.addWidget(self.label_2)
#         self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
#         self.label_7.setObjectName("label_7")
#         self.verticalLayout_2.addWidget(self.label_7)
#         self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
#         self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 290, 321, 41))
#         self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
#         self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
#         self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.Clanse = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
#         self.Clanse.setObjectName("Clanse")
#         self.horizontalLayout.addWidget(self.Clanse)
#         self.Ok = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
#         self.Ok.setObjectName("Ok")
#         self.horizontalLayout.addWidget(self.Ok)
#
#         self.retranslateUi(Dialog)
#         self.Clanse.clicked.connect(Dialog.close) # type: ignore
#         QtCore.QMetaObject.connectSlotsByName(Dialog)
#
#     def retranslateUi(self, Dialog):
#         _translate = QtCore.QCoreApplication.translate
#         Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
#         self.label_4.setText(_translate("Dialog", "Имя Входа"))
#         self.label_6.setText(_translate("Dialog", "ФИО"))
#         self.label_5.setText(_translate("Dialog", "Адрес"))
#         self.label_3.setText(_translate("Dialog", "Контакты"))
#         self.label_2.setText(_translate("Dialog", "Примечания"))
#         #self.label.setText(_translate("Dialog", "что то еще"))
#         self.Clanse.setText(_translate("Dialog", "Отмена"))
#         self.Ok.setText(_translate("Dialog", "Ок"))